Repository equinor/isar-robot, pull requests merged in 2023-03, with the labels that each got.

#58 Push images to aurora dev and prod
  .github/workflows/publish_docker_image.yml
Labels: improvement

#61 Pin ISAR version
  Dockerfile
Labels: improvement

#63 Add audio recording to capabilities
  src/isar_robot/config/settings.env
Labels: feature

#64 Set ISAR version to 1.13.2
  Dockerfile
Labels: improvement

#65 Include settings.env on build
  setup.py
Labels: bug
